// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sybild.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	sybild.proto

It has these top-level messages:
	IngestRequest
	IngestResponse
	QueryFilter
	QueryRequest
	Histogram
	QueryResult
	ResultMap
	SetField
	Record
	QueryResults
	QueryResponse
	ListTablesRequest
	ListTablesResponse
	GetTableRequest
	Table
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/struct"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// QueryType defines the types of query that can be performed.
type QueryType int32

const (
	QueryType_QUERY_TYPE_UNKNOWN QueryType = 0
	QueryType_TABLE              QueryType = 1
	QueryType_TIME_SERIES        QueryType = 2
	QueryType_DISTRIBUTION       QueryType = 3
	QueryType_SAMPLES            QueryType = 4
)

var QueryType_name = map[int32]string{
	0: "QUERY_TYPE_UNKNOWN",
	1: "TABLE",
	2: "TIME_SERIES",
	3: "DISTRIBUTION",
	4: "SAMPLES",
}
var QueryType_value = map[string]int32{
	"QUERY_TYPE_UNKNOWN": 0,
	"TABLE":              1,
	"TIME_SERIES":        2,
	"DISTRIBUTION":       3,
	"SAMPLES":            4,
}

func (x QueryType) String() string {
	return proto.EnumName(QueryType_name, int32(x))
}
func (QueryType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// QueryOp
type QueryOp int32

const (
	QueryOp_QUERY_OP_UNKNOWN QueryOp = 0
	QueryOp_AVERAGE          QueryOp = 1
	QueryOp_HISTOGRAM        QueryOp = 2
)

var QueryOp_name = map[int32]string{
	0: "QUERY_OP_UNKNOWN",
	1: "AVERAGE",
	2: "HISTOGRAM",
}
var QueryOp_value = map[string]int32{
	"QUERY_OP_UNKNOWN": 0,
	"AVERAGE":          1,
	"HISTOGRAM":        2,
}

func (x QueryOp) String() string {
	return proto.EnumName(QueryOp_name, int32(x))
}
func (QueryOp) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// QueryFilterOp
type QueryFilterOp int32

const (
	QueryFilterOp_QUERY_FILTER_OP_UNKNOWN QueryFilterOp = 0
	QueryFilterOp_RE                      QueryFilterOp = 1
	QueryFilterOp_NRE                     QueryFilterOp = 2
	QueryFilterOp_EQ                      QueryFilterOp = 3
	QueryFilterOp_NEQ                     QueryFilterOp = 4
	QueryFilterOp_GT                      QueryFilterOp = 5
	QueryFilterOp_LT                      QueryFilterOp = 6
	QueryFilterOp_IN                      QueryFilterOp = 7
	QueryFilterOp_NIN                     QueryFilterOp = 8
)

var QueryFilterOp_name = map[int32]string{
	0: "QUERY_FILTER_OP_UNKNOWN",
	1: "RE",
	2: "NRE",
	3: "EQ",
	4: "NEQ",
	5: "GT",
	6: "LT",
	7: "IN",
	8: "NIN",
}
var QueryFilterOp_value = map[string]int32{
	"QUERY_FILTER_OP_UNKNOWN": 0,
	"RE":  1,
	"NRE": 2,
	"EQ":  3,
	"NEQ": 4,
	"GT":  5,
	"LT":  6,
	"IN":  7,
	"NIN": 8,
}

func (x QueryFilterOp) String() string {
	return proto.EnumName(QueryFilterOp_name, int32(x))
}
func (QueryFilterOp) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// IngestRequest inserts records into a sybil dataset.
type IngestRequest struct {
	// dataset is the name of the dataset.
	Dataset string `protobuf:"bytes,1,opt,name=dataset" json:"dataset,omitempty"`
	// records is the set of records to insert.
	Records []*google_protobuf.Struct `protobuf:"bytes,2,rep,name=records" json:"records,omitempty"`
}

func (m *IngestRequest) Reset()                    { *m = IngestRequest{} }
func (m *IngestRequest) String() string            { return proto.CompactTextString(m) }
func (*IngestRequest) ProtoMessage()               {}
func (*IngestRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *IngestRequest) GetDataset() string {
	if m != nil {
		return m.Dataset
	}
	return ""
}

func (m *IngestRequest) GetRecords() []*google_protobuf.Struct {
	if m != nil {
		return m.Records
	}
	return nil
}

// IngestResponse reports the results of an ingestion request.
type IngestResponse struct {
	NumberInserted int64 `protobuf:"varint,1,opt,name=number_inserted,json=numberInserted" json:"number_inserted,omitempty"`
}

func (m *IngestResponse) Reset()                    { *m = IngestResponse{} }
func (m *IngestResponse) String() string            { return proto.CompactTextString(m) }
func (*IngestResponse) ProtoMessage()               {}
func (*IngestResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *IngestResponse) GetNumberInserted() int64 {
	if m != nil {
		return m.NumberInserted
	}
	return 0
}

// QueryFilter
type QueryFilter struct {
	Column string        `protobuf:"bytes,1,opt,name=column" json:"column,omitempty"`
	Op     QueryFilterOp `protobuf:"varint,2,opt,name=op,enum=pb.QueryFilterOp" json:"op,omitempty"`
	Value  string        `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"`
}

func (m *QueryFilter) Reset()                    { *m = QueryFilter{} }
func (m *QueryFilter) String() string            { return proto.CompactTextString(m) }
func (*QueryFilter) ProtoMessage()               {}
func (*QueryFilter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *QueryFilter) GetColumn() string {
	if m != nil {
		return m.Column
	}
	return ""
}

func (m *QueryFilter) GetOp() QueryFilterOp {
	if m != nil {
		return m.Op
	}
	return QueryFilterOp_QUERY_FILTER_OP_UNKNOWN
}

func (m *QueryFilter) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// QueryRequest
type QueryRequest struct {
	// dataset is the name of the dataset.
	Dataset                string         `protobuf:"bytes,1,opt,name=dataset" json:"dataset,omitempty"`
	Type                   QueryType      `protobuf:"varint,2,opt,name=type,enum=pb.QueryType" json:"type,omitempty"`
	Limit                  int64          `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
	Ints                   []string       `protobuf:"bytes,4,rep,name=ints" json:"ints,omitempty"`
	Strs                   []string       `protobuf:"bytes,5,rep,name=strs" json:"strs,omitempty"`
	Groups                 []string       `protobuf:"bytes,6,rep,name=groups" json:"groups,omitempty"`
	DistinctBy             []string       `protobuf:"bytes,7,rep,name=distinct_by,json=distinctBy" json:"distinct_by,omitempty"`
	Sort                   string         `protobuf:"bytes,8,opt,name=sort" json:"sort,omitempty"`
	TimeColumn             string         `protobuf:"bytes,9,opt,name=time_column,json=timeColumn" json:"time_column,omitempty"`
	TimeBucket             int64          `protobuf:"varint,10,opt,name=time_bucket,json=timeBucket" json:"time_bucket,omitempty"`
	Op                     QueryOp        `protobuf:"varint,11,opt,name=op,enum=pb.QueryOp" json:"op,omitempty"`
	LogHistogram           bool           `protobuf:"varint,12,opt,name=log_histogram,json=logHistogram" json:"log_histogram,omitempty"`
	IntFilters             []*QueryFilter `protobuf:"bytes,13,rep,name=int_filters,json=intFilters" json:"int_filters,omitempty"`
	StrFilters             []*QueryFilter `protobuf:"bytes,14,rep,name=str_filters,json=strFilters" json:"str_filters,omitempty"`
	SetFilters             []*QueryFilter `protobuf:"bytes,15,rep,name=set_filters,json=setFilters" json:"set_filters,omitempty"`
	IntHistogramBucketSize int64          `protobuf:"varint,16,opt,name=int_histogram_bucket_size,json=intHistogramBucketSize" json:"int_histogram_bucket_size,omitempty"`
}

func (m *QueryRequest) Reset()                    { *m = QueryRequest{} }
func (m *QueryRequest) String() string            { return proto.CompactTextString(m) }
func (*QueryRequest) ProtoMessage()               {}
func (*QueryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *QueryRequest) GetDataset() string {
	if m != nil {
		return m.Dataset
	}
	return ""
}

func (m *QueryRequest) GetType() QueryType {
	if m != nil {
		return m.Type
	}
	return QueryType_QUERY_TYPE_UNKNOWN
}

func (m *QueryRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *QueryRequest) GetInts() []string {
	if m != nil {
		return m.Ints
	}
	return nil
}

func (m *QueryRequest) GetStrs() []string {
	if m != nil {
		return m.Strs
	}
	return nil
}

func (m *QueryRequest) GetGroups() []string {
	if m != nil {
		return m.Groups
	}
	return nil
}

func (m *QueryRequest) GetDistinctBy() []string {
	if m != nil {
		return m.DistinctBy
	}
	return nil
}

func (m *QueryRequest) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

func (m *QueryRequest) GetTimeColumn() string {
	if m != nil {
		return m.TimeColumn
	}
	return ""
}

func (m *QueryRequest) GetTimeBucket() int64 {
	if m != nil {
		return m.TimeBucket
	}
	return 0
}

func (m *QueryRequest) GetOp() QueryOp {
	if m != nil {
		return m.Op
	}
	return QueryOp_QUERY_OP_UNKNOWN
}

func (m *QueryRequest) GetLogHistogram() bool {
	if m != nil {
		return m.LogHistogram
	}
	return false
}

func (m *QueryRequest) GetIntFilters() []*QueryFilter {
	if m != nil {
		return m.IntFilters
	}
	return nil
}

func (m *QueryRequest) GetStrFilters() []*QueryFilter {
	if m != nil {
		return m.StrFilters
	}
	return nil
}

func (m *QueryRequest) GetSetFilters() []*QueryFilter {
	if m != nil {
		return m.SetFilters
	}
	return nil
}

func (m *QueryRequest) GetIntHistogramBucketSize() int64 {
	if m != nil {
		return m.IntHistogramBucketSize
	}
	return 0
}

// Histogram
type Histogram struct {
	Mean         float64         `protobuf:"fixed64,1,opt,name=mean" json:"mean,omitempty"`
	Max          int64           `protobuf:"varint,2,opt,name=max" json:"max,omitempty"`
	Min          int64           `protobuf:"varint,3,opt,name=min" json:"min,omitempty"`
	TotalCount   int64           `protobuf:"varint,4,opt,name=total_count,json=totalCount" json:"total_count,omitempty"`
	Percentiles  []int64         `protobuf:"varint,5,rep,packed,name=percentiles" json:"percentiles,omitempty"`
	IntBuckets   map[int64]int64 `protobuf:"bytes,6,rep,name=int_buckets,json=intBuckets" json:"int_buckets,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	RangeStart   int64           `protobuf:"varint,7,opt,name=range_start,json=rangeStart" json:"range_start,omitempty"`
	RangeEnd     int64           `protobuf:"varint,8,opt,name=range_end,json=rangeEnd" json:"range_end,omitempty"`
	StdDeviation float64         `protobuf:"fixed64,9,opt,name=std_deviation,json=stdDeviation" json:"std_deviation,omitempty"`
}

func (m *Histogram) Reset()                    { *m = Histogram{} }
func (m *Histogram) String() string            { return proto.CompactTextString(m) }
func (*Histogram) ProtoMessage()               {}
func (*Histogram) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Histogram) GetMean() float64 {
	if m != nil {
		return m.Mean
	}
	return 0
}

func (m *Histogram) GetMax() int64 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *Histogram) GetMin() int64 {
	if m != nil {
		return m.Min
	}
	return 0
}

func (m *Histogram) GetTotalCount() int64 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *Histogram) GetPercentiles() []int64 {
	if m != nil {
		return m.Percentiles
	}
	return nil
}

func (m *Histogram) GetIntBuckets() map[int64]int64 {
	if m != nil {
		return m.IntBuckets
	}
	return nil
}

func (m *Histogram) GetRangeStart() int64 {
	if m != nil {
		return m.RangeStart
	}
	return 0
}

func (m *Histogram) GetRangeEnd() int64 {
	if m != nil {
		return m.RangeEnd
	}
	return 0
}

func (m *Histogram) GetStdDeviation() float64 {
	if m != nil {
		return m.StdDeviation
	}
	return 0
}

// QueryResult
type QueryResult struct {
	Histograms map[string]*Histogram `protobuf:"bytes,1,rep,name=histograms" json:"histograms,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	GroupByKey string                `protobuf:"bytes,3,opt,name=GroupByKey" json:"GroupByKey,omitempty"`
	Count      int64                 `protobuf:"varint,4,opt,name=Count" json:"Count,omitempty"`
	Samples    int64                 `protobuf:"varint,5,opt,name=Samples" json:"Samples,omitempty"`
}

func (m *QueryResult) Reset()                    { *m = QueryResult{} }
func (m *QueryResult) String() string            { return proto.CompactTextString(m) }
func (*QueryResult) ProtoMessage()               {}
func (*QueryResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *QueryResult) GetHistograms() map[string]*Histogram {
	if m != nil {
		return m.Histograms
	}
	return nil
}

func (m *QueryResult) GetGroupByKey() string {
	if m != nil {
		return m.GroupByKey
	}
	return ""
}

func (m *QueryResult) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *QueryResult) GetSamples() int64 {
	if m != nil {
		return m.Samples
	}
	return 0
}

// ResultMap
type ResultMap struct {
	Values map[string]*QueryResult `protobuf:"bytes,1,rep,name=values" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *ResultMap) Reset()                    { *m = ResultMap{} }
func (m *ResultMap) String() string            { return proto.CompactTextString(m) }
func (*ResultMap) ProtoMessage()               {}
func (*ResultMap) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ResultMap) GetValues() map[string]*QueryResult {
	if m != nil {
		return m.Values
	}
	return nil
}

// SetField
type SetField struct {
	Values []string `protobuf:"bytes,1,rep,name=values" json:"values,omitempty"`
}

func (m *SetField) Reset()                    { *m = SetField{} }
func (m *SetField) String() string            { return proto.CompactTextString(m) }
func (*SetField) ProtoMessage()               {}
func (*SetField) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *SetField) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

// Record
type Record struct {
	Strs map[string]string    `protobuf:"bytes,1,rep,name=strs" json:"strs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Ints map[string]int64     `protobuf:"bytes,2,rep,name=ints" json:"ints,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Sets map[string]*SetField `protobuf:"bytes,3,rep,name=sets" json:"sets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Record) Reset()                    { *m = Record{} }
func (m *Record) String() string            { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()               {}
func (*Record) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Record) GetStrs() map[string]string {
	if m != nil {
		return m.Strs
	}
	return nil
}

func (m *Record) GetInts() map[string]int64 {
	if m != nil {
		return m.Ints
	}
	return nil
}

func (m *Record) GetSets() map[string]*SetField {
	if m != nil {
		return m.Sets
	}
	return nil
}

// QueryResults
type QueryResults struct {
	Cumulative   *QueryResult         `protobuf:"bytes,1,opt,name=cumulative" json:"cumulative,omitempty"`
	Results      *ResultMap           `protobuf:"bytes,2,opt,name=results" json:"results,omitempty"`
	TimeResults  map[int64]*ResultMap `protobuf:"bytes,3,rep,name=time_results,json=timeResults" json:"time_results,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MatchedCount int64                `protobuf:"varint,4,opt,name=matched_count,json=matchedCount" json:"matched_count,omitempty"`
	Sorted       []*QueryResult       `protobuf:"bytes,5,rep,name=sorted" json:"sorted,omitempty"`
	Matched      []*Record            `protobuf:"bytes,6,rep,name=matched" json:"matched,omitempty"`
}

func (m *QueryResults) Reset()                    { *m = QueryResults{} }
func (m *QueryResults) String() string            { return proto.CompactTextString(m) }
func (*QueryResults) ProtoMessage()               {}
func (*QueryResults) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *QueryResults) GetCumulative() *QueryResult {
	if m != nil {
		return m.Cumulative
	}
	return nil
}

func (m *QueryResults) GetResults() *ResultMap {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *QueryResults) GetTimeResults() map[int64]*ResultMap {
	if m != nil {
		return m.TimeResults
	}
	return nil
}

func (m *QueryResults) GetMatchedCount() int64 {
	if m != nil {
		return m.MatchedCount
	}
	return 0
}

func (m *QueryResults) GetSorted() []*QueryResult {
	if m != nil {
		return m.Sorted
	}
	return nil
}

func (m *QueryResults) GetMatched() []*Record {
	if m != nil {
		return m.Matched
	}
	return nil
}

// QueryResponse
type QueryResponse struct {
	Results *QueryResults `protobuf:"bytes,1,opt,name=results" json:"results,omitempty"`
}

func (m *QueryResponse) Reset()                    { *m = QueryResponse{} }
func (m *QueryResponse) String() string            { return proto.CompactTextString(m) }
func (*QueryResponse) ProtoMessage()               {}
func (*QueryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *QueryResponse) GetResults() *QueryResults {
	if m != nil {
		return m.Results
	}
	return nil
}

// ListTablesRequest
type ListTablesRequest struct {
}

func (m *ListTablesRequest) Reset()                    { *m = ListTablesRequest{} }
func (m *ListTablesRequest) String() string            { return proto.CompactTextString(m) }
func (*ListTablesRequest) ProtoMessage()               {}
func (*ListTablesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

// ListTablesResponse
type ListTablesResponse struct {
	Tables []string `protobuf:"bytes,1,rep,name=tables" json:"tables,omitempty"`
}

func (m *ListTablesResponse) Reset()                    { *m = ListTablesResponse{} }
func (m *ListTablesResponse) String() string            { return proto.CompactTextString(m) }
func (*ListTablesResponse) ProtoMessage()               {}
func (*ListTablesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *ListTablesResponse) GetTables() []string {
	if m != nil {
		return m.Tables
	}
	return nil
}

// GetTableRequest
type GetTableRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *GetTableRequest) Reset()                    { *m = GetTableRequest{} }
func (m *GetTableRequest) String() string            { return proto.CompactTextString(m) }
func (*GetTableRequest) ProtoMessage()               {}
func (*GetTableRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *GetTableRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// Table
type Table struct {
	Name              string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	StrColumns        []string `protobuf:"bytes,2,rep,name=str_columns,json=strColumns" json:"str_columns,omitempty"`
	IntColumns        []string `protobuf:"bytes,3,rep,name=int_columns,json=intColumns" json:"int_columns,omitempty"`
	SetColumns        []string `protobuf:"bytes,4,rep,name=set_columns,json=setColumns" json:"set_columns,omitempty"`
	Count             int64    `protobuf:"varint,5,opt,name=count" json:"count,omitempty"`
	StorageSize       int64    `protobuf:"varint,6,opt,name=storage_size,json=storageSize" json:"storage_size,omitempty"`
	AverageObjectSize int64    `protobuf:"varint,7,opt,name=average_object_size,json=averageObjectSize" json:"average_object_size,omitempty"`
}

func (m *Table) Reset()                    { *m = Table{} }
func (m *Table) String() string            { return proto.CompactTextString(m) }
func (*Table) ProtoMessage()               {}
func (*Table) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *Table) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Table) GetStrColumns() []string {
	if m != nil {
		return m.StrColumns
	}
	return nil
}

func (m *Table) GetIntColumns() []string {
	if m != nil {
		return m.IntColumns
	}
	return nil
}

func (m *Table) GetSetColumns() []string {
	if m != nil {
		return m.SetColumns
	}
	return nil
}

func (m *Table) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *Table) GetStorageSize() int64 {
	if m != nil {
		return m.StorageSize
	}
	return 0
}

func (m *Table) GetAverageObjectSize() int64 {
	if m != nil {
		return m.AverageObjectSize
	}
	return 0
}

func init() {
	proto.RegisterType((*IngestRequest)(nil), "pb.IngestRequest")
	proto.RegisterType((*IngestResponse)(nil), "pb.IngestResponse")
	proto.RegisterType((*QueryFilter)(nil), "pb.QueryFilter")
	proto.RegisterType((*QueryRequest)(nil), "pb.QueryRequest")
	proto.RegisterType((*Histogram)(nil), "pb.Histogram")
	proto.RegisterType((*QueryResult)(nil), "pb.QueryResult")
	proto.RegisterType((*ResultMap)(nil), "pb.ResultMap")
	proto.RegisterType((*SetField)(nil), "pb.SetField")
	proto.RegisterType((*Record)(nil), "pb.Record")
	proto.RegisterType((*QueryResults)(nil), "pb.QueryResults")
	proto.RegisterType((*QueryResponse)(nil), "pb.QueryResponse")
	proto.RegisterType((*ListTablesRequest)(nil), "pb.ListTablesRequest")
	proto.RegisterType((*ListTablesResponse)(nil), "pb.ListTablesResponse")
	proto.RegisterType((*GetTableRequest)(nil), "pb.GetTableRequest")
	proto.RegisterType((*Table)(nil), "pb.Table")
	proto.RegisterEnum("pb.QueryType", QueryType_name, QueryType_value)
	proto.RegisterEnum("pb.QueryOp", QueryOp_name, QueryOp_value)
	proto.RegisterEnum("pb.QueryFilterOp", QueryFilterOp_name, QueryFilterOp_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Sybil service

type SybilClient interface {
	// Ingest inserts new data into a sybil dataset.
	Ingest(ctx context.Context, in *IngestRequest, opts ...grpc.CallOption) (*IngestResponse, error)
	// Query retrieves results from sybil.
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	// ListTables lists the tables in a sybil database.
	ListTables(ctx context.Context, in *ListTablesRequest, opts ...grpc.CallOption) (*ListTablesResponse, error)
	// GetTable gets details about a particular table.
	GetTable(ctx context.Context, in *GetTableRequest, opts ...grpc.CallOption) (*Table, error)
}

type sybilClient struct {
	cc *grpc.ClientConn
}

func NewSybilClient(cc *grpc.ClientConn) SybilClient {
	return &sybilClient{cc}
}

func (c *sybilClient) Ingest(ctx context.Context, in *IngestRequest, opts ...grpc.CallOption) (*IngestResponse, error) {
	out := new(IngestResponse)
	err := grpc.Invoke(ctx, "/pb.Sybil/Ingest", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sybilClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	out := new(QueryResponse)
	err := grpc.Invoke(ctx, "/pb.Sybil/Query", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sybilClient) ListTables(ctx context.Context, in *ListTablesRequest, opts ...grpc.CallOption) (*ListTablesResponse, error) {
	out := new(ListTablesResponse)
	err := grpc.Invoke(ctx, "/pb.Sybil/ListTables", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sybilClient) GetTable(ctx context.Context, in *GetTableRequest, opts ...grpc.CallOption) (*Table, error) {
	out := new(Table)
	err := grpc.Invoke(ctx, "/pb.Sybil/GetTable", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Sybil service

type SybilServer interface {
	// Ingest inserts new data into a sybil dataset.
	Ingest(context.Context, *IngestRequest) (*IngestResponse, error)
	// Query retrieves results from sybil.
	Query(context.Context, *QueryRequest) (*QueryResponse, error)
	// ListTables lists the tables in a sybil database.
	ListTables(context.Context, *ListTablesRequest) (*ListTablesResponse, error)
	// GetTable gets details about a particular table.
	GetTable(context.Context, *GetTableRequest) (*Table, error)
}

func RegisterSybilServer(s *grpc.Server, srv SybilServer) {
	s.RegisterService(&_Sybil_serviceDesc, srv)
}

func _Sybil_Ingest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SybilServer).Ingest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Sybil/Ingest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SybilServer).Ingest(ctx, req.(*IngestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sybil_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SybilServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Sybil/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SybilServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sybil_ListTables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SybilServer).ListTables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Sybil/ListTables",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SybilServer).ListTables(ctx, req.(*ListTablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sybil_GetTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SybilServer).GetTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Sybil/GetTable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SybilServer).GetTable(ctx, req.(*GetTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Sybil_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Sybil",
	HandlerType: (*SybilServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ingest",
			Handler:    _Sybil_Ingest_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _Sybil_Query_Handler,
		},
		{
			MethodName: "ListTables",
			Handler:    _Sybil_ListTables_Handler,
		},
		{
			MethodName: "GetTable",
			Handler:    _Sybil_GetTable_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sybild.proto",
}

func init() { proto.RegisterFile("sybild.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1443 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x57, 0xed, 0x72, 0xd3, 0x46,
	0x17, 0xc6, 0x92, 0x3f, 0xa2, 0x23, 0x27, 0x56, 0x96, 0xbc, 0x41, 0x98, 0x79, 0x4b, 0x22, 0xca,
	0x90, 0xc9, 0x30, 0x4e, 0x49, 0xa7, 0xd3, 0x52, 0x86, 0x76, 0x12, 0x10, 0xc1, 0x25, 0x1f, 0x44,
	0x36, 0x74, 0x98, 0xe9, 0xe0, 0x91, 0xed, 0xc5, 0xa8, 0xc8, 0x92, 0xaa, 0x5d, 0x65, 0x6a, 0x2e,
	0xa1, 0xb7, 0xd2, 0x8b, 0xe8, 0x65, 0xf4, 0x12, 0xda, 0x1f, 0xfd, 0xd3, 0x3b, 0xe8, 0xec, 0xd9,
	0x95, 0xac, 0x18, 0x33, 0xfc, 0xf2, 0xee, 0x73, 0x3e, 0xf6, 0x9c, 0x67, 0x8f, 0xce, 0x59, 0x43,
	0x93, 0xcd, 0x86, 0x41, 0x38, 0xee, 0x24, 0x69, 0xcc, 0x63, 0xa2, 0x25, 0xc3, 0xf6, 0x57, 0x93,
	0x80, 0xbf, 0xcd, 0x86, 0x9d, 0x51, 0x3c, 0xdd, 0x9b, 0xc4, 0xa1, 0x1f, 0x4d, 0xf6, 0x50, 0x38,
	0xcc, 0xde, 0xec, 0x25, 0x7c, 0x96, 0x50, 0xb6, 0xc7, 0x78, 0x9a, 0x8d, 0xb8, 0xfa, 0x91, 0xa6,
	0xce, 0x4f, 0xb0, 0xda, 0x8d, 0x26, 0x94, 0x71, 0x8f, 0xfe, 0x92, 0x51, 0xc6, 0x89, 0x0d, 0x8d,
	0xb1, 0xcf, 0x7d, 0x46, 0xb9, 0x5d, 0xd9, 0xaa, 0xec, 0x18, 0x5e, 0xbe, 0x25, 0xf7, 0xa0, 0x91,
	0xd2, 0x51, 0x9c, 0x8e, 0x99, 0xad, 0x6d, 0xe9, 0x3b, 0xe6, 0xfe, 0xb5, 0xce, 0x24, 0x8e, 0x27,
	0x21, 0xed, 0xe4, 0x07, 0x75, 0x7a, 0xe8, 0xda, 0xcb, 0xf5, 0x9c, 0xfb, 0xb0, 0x96, 0x7b, 0x67,
	0x49, 0x1c, 0x31, 0x4a, 0xee, 0x40, 0x2b, 0xca, 0xa6, 0x43, 0x9a, 0x0e, 0x82, 0x88, 0xd1, 0x94,
	0xd3, 0x31, 0x1e, 0xa3, 0x7b, 0x6b, 0x12, 0xee, 0x2a, 0xd4, 0x79, 0x0d, 0xe6, 0x79, 0x46, 0xd3,
	0xd9, 0x93, 0x20, 0xe4, 0x34, 0x25, 0x9b, 0x50, 0x1f, 0xc5, 0x61, 0x36, 0x8d, 0x54, 0x54, 0x6a,
	0x47, 0xb6, 0x41, 0x8b, 0x13, 0x5b, 0xdb, 0xaa, 0xec, 0xac, 0xed, 0xaf, 0x77, 0x92, 0x61, 0xa7,
	0x64, 0x74, 0x96, 0x78, 0x5a, 0x9c, 0x90, 0x0d, 0xa8, 0x5d, 0xf8, 0x61, 0x46, 0x6d, 0x1d, 0x2d,
	0xe5, 0xc6, 0xf9, 0xbd, 0x0a, 0x4d, 0xd4, 0xfd, 0x74, 0xe2, 0xdb, 0x50, 0x15, 0x04, 0xaa, 0x53,
	0x56, 0x8b, 0x53, 0xfa, 0xb3, 0x84, 0x7a, 0x28, 0x12, 0x67, 0x84, 0xc1, 0x34, 0xe0, 0x78, 0x86,
	0xee, 0xc9, 0x0d, 0x21, 0x50, 0x0d, 0x22, 0xce, 0xec, 0xea, 0x96, 0xbe, 0x63, 0x78, 0xb8, 0x16,
	0x18, 0xe3, 0x29, 0xb3, 0x6b, 0x12, 0x13, 0x6b, 0x91, 0xdc, 0x24, 0x8d, 0xb3, 0x84, 0xd9, 0x75,
	0x44, 0xd5, 0x8e, 0xdc, 0x04, 0x73, 0x1c, 0x30, 0x1e, 0x44, 0x23, 0x3e, 0x18, 0xce, 0xec, 0x06,
	0x0a, 0x21, 0x87, 0x0e, 0x67, 0xe8, 0x2c, 0x4e, 0xb9, 0xbd, 0x82, 0x01, 0xe3, 0x5a, 0x18, 0xf1,
	0x60, 0x4a, 0x07, 0x8a, 0x2e, 0x03, 0x45, 0x20, 0xa0, 0x47, 0x92, 0xb2, 0x5c, 0x61, 0x98, 0x8d,
	0xde, 0x51, 0x6e, 0x03, 0x46, 0x8c, 0x0a, 0x87, 0x88, 0x90, 0x1b, 0xc8, 0xa9, 0x89, 0xd9, 0x9a,
	0x45, 0xb6, 0x8a, 0xcd, 0x5b, 0xb0, 0x1a, 0xc6, 0x93, 0xc1, 0xdb, 0x80, 0xf1, 0x78, 0x92, 0xfa,
	0x53, 0xbb, 0xb9, 0x55, 0xd9, 0x59, 0xf1, 0x9a, 0x61, 0x3c, 0x79, 0x9a, 0x63, 0xe4, 0x0b, 0x30,
	0x83, 0x88, 0x0f, 0xde, 0xe0, 0x35, 0x30, 0x7b, 0x15, 0xcb, 0xa5, 0xb5, 0x70, 0x3d, 0x1e, 0x04,
	0x11, 0x97, 0x4b, 0x26, 0x2c, 0x18, 0x4f, 0x0b, 0x8b, 0xb5, 0x8f, 0x58, 0x30, 0x9e, 0x96, 0x2d,
	0xe8, 0xfc, 0x8c, 0xd6, 0xc7, 0x2c, 0x68, 0x71, 0xc6, 0x7d, 0xb8, 0x2e, 0xa2, 0x2a, 0x42, 0x57,
	0x0c, 0x0c, 0x58, 0xf0, 0x9e, 0xda, 0x16, 0xd2, 0xb0, 0x19, 0x44, 0xbc, 0x48, 0x43, 0xd2, 0xd1,
	0x0b, 0xde, 0x53, 0xe7, 0x6f, 0x0d, 0x8c, 0x79, 0x7a, 0x04, 0xaa, 0x53, 0xea, 0xcb, 0x52, 0xac,
	0x78, 0xb8, 0x26, 0x16, 0xe8, 0x53, 0xff, 0x57, 0xac, 0x11, 0xdd, 0x13, 0x4b, 0x44, 0x82, 0x48,
	0x55, 0x84, 0x58, 0x22, 0xf3, 0x31, 0xf7, 0xc3, 0xc1, 0x28, 0xce, 0x22, 0x6e, 0x57, 0x15, 0xf3,
	0x02, 0x7a, 0x24, 0x10, 0xb2, 0x05, 0x66, 0x42, 0xd3, 0x11, 0x8d, 0x78, 0x10, 0x52, 0x59, 0x23,
	0xba, 0x57, 0x86, 0xc8, 0x77, 0x92, 0x59, 0x19, 0xb9, 0xac, 0x17, 0x73, 0xff, 0xff, 0x22, 0xeb,
	0x22, 0xbc, 0x4e, 0x37, 0xe2, 0x32, 0x74, 0xe6, 0x46, 0x3c, 0x9d, 0x21, 0xcf, 0x0a, 0x10, 0x21,
	0xa4, 0x7e, 0x34, 0xa1, 0x03, 0xc6, 0xfd, 0x94, 0xdb, 0x0d, 0x19, 0x02, 0x42, 0x3d, 0x81, 0x90,
	0x1b, 0x60, 0x48, 0x05, 0x1a, 0x8d, 0xb1, 0xae, 0x74, 0x6f, 0x05, 0x01, 0x37, 0x1a, 0x8b, 0xcb,
	0x67, 0x7c, 0x3c, 0x18, 0xd3, 0x8b, 0xc0, 0xe7, 0x41, 0x2c, 0xab, 0xab, 0xe2, 0x35, 0x19, 0x1f,
	0x3f, 0xce, 0xb1, 0xf6, 0x43, 0x68, 0x2d, 0x44, 0x20, 0xa8, 0x78, 0x47, 0x67, 0xea, 0x4b, 0x17,
	0xcb, 0xf9, 0x47, 0x29, 0x09, 0x93, 0x9b, 0x6f, 0xb5, 0x6f, 0x2a, 0xce, 0x3f, 0x15, 0xf5, 0xe5,
	0x7b, 0x94, 0x65, 0x21, 0x27, 0xdf, 0x03, 0x14, 0x37, 0xc6, 0xec, 0x0a, 0x26, 0x7c, 0xb3, 0xb8,
	0x66, 0xa9, 0x34, 0x4f, 0x3e, 0x4f, 0x79, 0x6e, 0x42, 0x3e, 0x03, 0x38, 0x12, 0xdf, 0xd3, 0xe1,
	0xec, 0x19, 0x9d, 0xa9, 0x26, 0x50, 0x42, 0x44, 0x28, 0x8f, 0x4a, 0xf7, 0x21, 0x37, 0xa2, 0x1d,
	0xf4, 0xfc, 0x69, 0x22, 0xaf, 0x41, 0xe0, 0xf9, 0xb6, 0x7d, 0x0c, 0xad, 0x85, 0xe3, 0xca, 0xf9,
	0x19, 0x32, 0xbf, 0x5b, 0xe5, 0xfc, 0x4c, 0xd9, 0x34, 0x0a, 0xab, 0x72, 0xba, 0xbf, 0x55, 0xc0,
	0x90, 0x49, 0x9c, 0xf8, 0x09, 0xb9, 0x07, 0x75, 0x14, 0xe5, 0x89, 0x5e, 0x17, 0x76, 0x85, 0xb8,
	0xf3, 0x12, 0x65, 0x32, 0x45, 0xa5, 0xd8, 0xfe, 0x01, 0xcc, 0x12, 0xbc, 0x24, 0x94, 0xdb, 0x97,
	0x43, 0x69, 0x2d, 0x70, 0x57, 0x0e, 0xc6, 0x81, 0x95, 0x9e, 0xf8, 0x5e, 0x68, 0x38, 0x16, 0x4d,
	0xa9, 0x14, 0x8a, 0x91, 0x9f, 0xe7, 0xfc, 0xa1, 0x41, 0xdd, 0xc3, 0xfe, 0x4e, 0x76, 0x54, 0x2f,
	0x93, 0xb1, 0x6e, 0xc8, 0x58, 0x85, 0x44, 0x0c, 0x02, 0x15, 0xa6, 0xec, 0x70, 0x3b, 0xaa, 0x13,
	0x6a, 0x1f, 0x68, 0x76, 0xa3, 0xbc, 0x4c, 0x65, 0x7f, 0x14, 0x3e, 0x45, 0x65, 0xeb, 0x1f, 0xfa,
	0x2c, 0x0a, 0x1a, 0x35, 0xda, 0x5f, 0x83, 0x51, 0x1c, 0xb3, 0x24, 0xed, 0x4b, 0x15, 0x66, 0x94,
	0xb2, 0x14, 0x86, 0xc5, 0xa9, 0x9f, 0x32, 0x2c, 0x97, 0x66, 0xdb, 0x05, 0xa3, 0x47, 0x3f, 0x6e,
	0xe8, 0x5c, 0x26, 0xba, 0x29, 0x62, 0xcf, 0xe9, 0x2c, 0xb3, 0xfc, 0xaf, 0x56, 0x8c, 0x1e, 0x71,
	0x01, 0x8c, 0xec, 0x01, 0x8c, 0xb2, 0x69, 0x16, 0xfa, 0x3c, 0xb8, 0xa0, 0xe8, 0x71, 0xc9, 0x35,
	0x95, 0x54, 0xc8, 0x1d, 0x31, 0x8a, 0xd1, 0xb6, 0x5c, 0x5f, 0x45, 0x9d, 0x78, 0xb9, 0x94, 0x3c,
	0x86, 0x26, 0xf6, 0xfa, 0x5c, 0x5b, 0xb2, 0xba, 0xbd, 0xe0, 0x9b, 0x75, 0xfa, 0xc1, 0x94, 0xaa,
	0xb5, 0xa4, 0x18, 0x47, 0x44, 0x1e, 0xdf, 0x2d, 0x58, 0x9d, 0xfa, 0x7c, 0xf4, 0x96, 0x8e, 0x2f,
	0x75, 0xae, 0xa6, 0x02, 0xe5, 0x07, 0x73, 0x07, 0xea, 0x62, 0xfe, 0xd0, 0x31, 0xb6, 0xad, 0x25,
	0x09, 0x28, 0x31, 0xf9, 0x1c, 0x1a, 0xca, 0x50, 0xb5, 0x2f, 0x98, 0x5f, 0xb2, 0x97, 0x8b, 0xda,
	0x27, 0x60, 0x2d, 0x06, 0xb5, 0xa4, 0x8d, 0x2c, 0xfb, 0xcc, 0xe6, 0x34, 0x94, 0x38, 0x7f, 0x00,
	0xab, 0x79, 0x2c, 0xf2, 0x21, 0xb2, 0x3b, 0xa7, 0x50, 0x12, 0x6e, 0x2d, 0x92, 0x52, 0xb0, 0xe8,
	0x5c, 0x85, 0xf5, 0xe3, 0x80, 0xf1, 0xbe, 0x3f, 0x0c, 0x29, 0x53, 0xef, 0x05, 0xe7, 0x2e, 0x90,
	0x32, 0xa8, 0xdc, 0x6e, 0x42, 0x9d, 0x23, 0x92, 0x7f, 0x35, 0x72, 0xe7, 0xdc, 0x86, 0xd6, 0x11,
	0x95, 0xca, 0xf9, 0x83, 0x83, 0x40, 0x35, 0xf2, 0xa7, 0x54, 0x55, 0x10, 0xae, 0x9d, 0xbf, 0x2a,
	0x50, 0x43, 0xa5, 0x65, 0x52, 0xd1, 0xbc, 0xc5, 0x90, 0x94, 0x93, 0x5d, 0x7e, 0x4c, 0x06, 0xce,
	0x44, 0x39, 0xd9, 0xb1, 0xbb, 0x8b, 0xe9, 0x90, 0x2b, 0xe8, 0x52, 0x21, 0x88, 0x78, 0x49, 0x41,
	0x0c, 0xcd, 0x5c, 0xa1, 0xaa, 0x3c, 0xd0, 0x42, 0x61, 0x03, 0x6a, 0xf2, 0x8a, 0x65, 0xd3, 0x93,
	0x1b, 0xb2, 0x0d, 0x4d, 0xc6, 0xe3, 0xd4, 0x17, 0x73, 0x43, 0x0c, 0xcb, 0x3a, 0x0a, 0x4d, 0x85,
	0x89, 0x09, 0x49, 0x3a, 0x70, 0xd5, 0xbf, 0xa0, 0xa8, 0x12, 0x0f, 0x7f, 0xa6, 0x23, 0x35, 0x56,
	0xe5, 0x80, 0x59, 0x57, 0xa2, 0x33, 0x94, 0x08, 0xfd, 0xdd, 0xd7, 0x60, 0x14, 0x8f, 0x28, 0xb2,
	0x09, 0xe4, 0xfc, 0x85, 0xeb, 0xbd, 0x1a, 0xf4, 0x5f, 0x3d, 0x77, 0x07, 0x2f, 0x4e, 0x9f, 0x9d,
	0x9e, 0xfd, 0x78, 0x6a, 0x5d, 0x21, 0x06, 0xd4, 0xfa, 0x07, 0x87, 0xc7, 0xae, 0x55, 0x21, 0x2d,
	0x30, 0xfb, 0xdd, 0x13, 0x77, 0xd0, 0x73, 0xbd, 0xae, 0xdb, 0xb3, 0x34, 0x62, 0x41, 0xf3, 0x71,
	0xb7, 0xd7, 0xf7, 0xba, 0x87, 0x2f, 0xfa, 0xdd, 0xb3, 0x53, 0x4b, 0x27, 0x26, 0x34, 0x7a, 0x07,
	0x27, 0xcf, 0x8f, 0xdd, 0x9e, 0x55, 0xdd, 0x7d, 0x00, 0x0d, 0xf5, 0x6c, 0x21, 0x1b, 0x60, 0x49,
	0xef, 0x67, 0xcf, 0x4b, 0xbe, 0x4d, 0x68, 0x1c, 0xbc, 0x74, 0xbd, 0x83, 0x23, 0xe1, 0x7d, 0x15,
	0x8c, 0xa7, 0xdd, 0x5e, 0xff, 0xec, 0xc8, 0x3b, 0x38, 0xb1, 0xb4, 0xdd, 0x58, 0x55, 0x4b, 0xfe,
	0x8e, 0x24, 0x37, 0xe0, 0x9a, 0x74, 0xf1, 0xa4, 0x7b, 0xdc, 0x77, 0xbd, 0xcb, 0x9e, 0xea, 0xa0,
	0x79, 0xc2, 0x49, 0x03, 0xf4, 0x53, 0xcf, 0xb5, 0x34, 0x01, 0xb8, 0xe7, 0x96, 0x8e, 0x80, 0x7b,
	0x6e, 0x55, 0x05, 0x70, 0xd4, 0xb7, 0x6a, 0xe2, 0xf7, 0xb8, 0x6f, 0xd5, 0xc5, 0x6f, 0xf7, 0xd4,
	0x6a, 0xa0, 0x42, 0xf7, 0xd4, 0x5a, 0xd9, 0xff, 0xb3, 0x02, 0xb5, 0x9e, 0x78, 0xd2, 0x8b, 0x09,
	0x20, 0x9f, 0xcc, 0x04, 0x9f, 0xb3, 0x97, 0x1e, 0xe7, 0x6d, 0x52, 0x86, 0x64, 0xc5, 0x39, 0x57,
	0x48, 0x07, 0x6a, 0x18, 0x2d, 0x29, 0x97, 0xb0, 0x34, 0x58, 0x2f, 0x17, 0x75, 0xae, 0xff, 0x10,
	0x60, 0x5e, 0xb9, 0xe4, 0x7f, 0x42, 0xe5, 0x83, 0xf2, 0x6e, 0x6f, 0x2e, 0xc2, 0x85, 0xf9, 0x5d,
	0x58, 0xc9, 0x4b, 0x99, 0x5c, 0x15, 0x5a, 0x0b, 0x85, 0xdd, 0x36, 0x04, 0x88, 0x88, 0x73, 0x65,
	0x58, 0xc7, 0x3f, 0x07, 0x5f, 0xfe, 0x17, 0x00, 0x00, 0xff, 0xff, 0x32, 0xd5, 0x03, 0x57, 0xb2,
	0x0c, 0x00, 0x00,
}
