// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sybild.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	sybild.proto

It has these top-level messages:
	IngestRequest
	IngestResponse
	QueryFilter
	QueryRequest
	HistogramOptions
	Histogram
	ResultMap
	SetField
	Record
	FieldValue
	QueryResult
	QueryResponse
	ListTablesRequest
	ListTablesResponse
	GetTableRequest
	Table
	TrimRequest
	TrimResponse
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/struct"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// QueryType defines the types of query that can be performed.
type QueryType int32

const (
	QueryType_QUERY_TYPE_UNKNOWN QueryType = 0
	QueryType_TABLE              QueryType = 1
	QueryType_TIME_SERIES        QueryType = 2
	QueryType_DISTRIBUTION       QueryType = 3
	QueryType_SAMPLES            QueryType = 4
)

var QueryType_name = map[int32]string{
	0: "QUERY_TYPE_UNKNOWN",
	1: "TABLE",
	2: "TIME_SERIES",
	3: "DISTRIBUTION",
	4: "SAMPLES",
}
var QueryType_value = map[string]int32{
	"QUERY_TYPE_UNKNOWN": 0,
	"TABLE":              1,
	"TIME_SERIES":        2,
	"DISTRIBUTION":       3,
	"SAMPLES":            4,
}

func (x QueryType) String() string {
	return proto.EnumName(QueryType_name, int32(x))
}
func (QueryType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// QueryOp is the type of operation to perform in the query.
type QueryOp int32

const (
	QueryOp_QUERY_OP_UNKNOWN QueryOp = 0
	QueryOp_AVERAGE          QueryOp = 1
	QueryOp_HISTOGRAM        QueryOp = 2
)

var QueryOp_name = map[int32]string{
	0: "QUERY_OP_UNKNOWN",
	1: "AVERAGE",
	2: "HISTOGRAM",
}
var QueryOp_value = map[string]int32{
	"QUERY_OP_UNKNOWN": 0,
	"AVERAGE":          1,
	"HISTOGRAM":        2,
}

func (x QueryOp) String() string {
	return proto.EnumName(QueryOp_name, int32(x))
}
func (QueryOp) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// QueryFilterOp is the operation to apply to a column as part of a QueryFilter.
type QueryFilterOp int32

const (
	QueryFilterOp_QUERY_FILTER_OP_UNKNOWN QueryFilterOp = 0
	QueryFilterOp_RE                      QueryFilterOp = 1
	QueryFilterOp_NRE                     QueryFilterOp = 2
	QueryFilterOp_EQ                      QueryFilterOp = 3
	QueryFilterOp_NEQ                     QueryFilterOp = 4
	QueryFilterOp_GT                      QueryFilterOp = 5
	QueryFilterOp_LT                      QueryFilterOp = 6
	QueryFilterOp_IN                      QueryFilterOp = 7
	QueryFilterOp_NIN                     QueryFilterOp = 8
)

var QueryFilterOp_name = map[int32]string{
	0: "QUERY_FILTER_OP_UNKNOWN",
	1: "RE",
	2: "NRE",
	3: "EQ",
	4: "NEQ",
	5: "GT",
	6: "LT",
	7: "IN",
	8: "NIN",
}
var QueryFilterOp_value = map[string]int32{
	"QUERY_FILTER_OP_UNKNOWN": 0,
	"RE":  1,
	"NRE": 2,
	"EQ":  3,
	"NEQ": 4,
	"GT":  5,
	"LT":  6,
	"IN":  7,
	"NIN": 8,
}

func (x QueryFilterOp) String() string {
	return proto.EnumName(QueryFilterOp_name, int32(x))
}
func (QueryFilterOp) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// HistogramType describes the type of histogram.
type HistogramType int32

const (
	HistogramType_HISTOGRAM_TYPE_UNKNOWN HistogramType = 0
	HistogramType_NORMAL_HISTOGRAM       HistogramType = 1
	HistogramType_LOG_HISTOGRAM          HistogramType = 2
)

var HistogramType_name = map[int32]string{
	0: "HISTOGRAM_TYPE_UNKNOWN",
	1: "NORMAL_HISTOGRAM",
	2: "LOG_HISTOGRAM",
}
var HistogramType_value = map[string]int32{
	"HISTOGRAM_TYPE_UNKNOWN": 0,
	"NORMAL_HISTOGRAM":       1,
	"LOG_HISTOGRAM":          2,
}

func (x HistogramType) String() string {
	return proto.EnumName(HistogramType_name, int32(x))
}
func (HistogramType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

// IngestRequest inserts records into a sybil dataset.
type IngestRequest struct {
	// Dataset is the name of the dataset.
	Dataset string `protobuf:"bytes,1,opt,name=dataset" json:"dataset,omitempty"`
	// Records is the set of records to insert.
	Records []*google_protobuf.Struct `protobuf:"bytes,2,rep,name=records" json:"records,omitempty"`
}

func (m *IngestRequest) Reset()                    { *m = IngestRequest{} }
func (m *IngestRequest) String() string            { return proto.CompactTextString(m) }
func (*IngestRequest) ProtoMessage()               {}
func (*IngestRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *IngestRequest) GetDataset() string {
	if m != nil {
		return m.Dataset
	}
	return ""
}

func (m *IngestRequest) GetRecords() []*google_protobuf.Struct {
	if m != nil {
		return m.Records
	}
	return nil
}

// IngestResponse reports the results of an ingestion request.
type IngestResponse struct {
	// The numer of inserted records.
	NumberInserted int64 `protobuf:"varint,1,opt,name=number_inserted,json=numberInserted" json:"number_inserted,omitempty"`
}

func (m *IngestResponse) Reset()                    { *m = IngestResponse{} }
func (m *IngestResponse) String() string            { return proto.CompactTextString(m) }
func (*IngestResponse) ProtoMessage()               {}
func (*IngestResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *IngestResponse) GetNumberInserted() int64 {
	if m != nil {
		return m.NumberInserted
	}
	return 0
}

// QueryFilter is a filter on a column.
type QueryFilter struct {
	Column string        `protobuf:"bytes,1,opt,name=column" json:"column,omitempty"`
	Op     QueryFilterOp `protobuf:"varint,2,opt,name=op,enum=pb.QueryFilterOp" json:"op,omitempty"`
	Value  string        `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"`
}

func (m *QueryFilter) Reset()                    { *m = QueryFilter{} }
func (m *QueryFilter) String() string            { return proto.CompactTextString(m) }
func (*QueryFilter) ProtoMessage()               {}
func (*QueryFilter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *QueryFilter) GetColumn() string {
	if m != nil {
		return m.Column
	}
	return ""
}

func (m *QueryFilter) GetOp() QueryFilterOp {
	if m != nil {
		return m.Op
	}
	return QueryFilterOp_QUERY_FILTER_OP_UNKNOWN
}

func (m *QueryFilter) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// QueryRequest describes a query.
type QueryRequest struct {
	// Dataset is the name of the dataset.
	Dataset string `protobuf:"bytes,1,opt,name=dataset" json:"dataset,omitempty"`
	// The type of the query.
	Type QueryType `protobuf:"varint,2,opt,name=type,enum=pb.QueryType" json:"type,omitempty"`
	// Limit number of results.
	Limit int64 `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
	// The integer fields to aggregate.
	Ints []string `protobuf:"bytes,4,rep,name=ints" json:"ints,omitempty"`
	// The string fields to aggregate.
	Strs []string `protobuf:"bytes,5,rep,name=strs" json:"strs,omitempty"`
	// The fields to group by.
	GroupBy         []string `protobuf:"bytes,6,rep,name=group_by,json=groupBy" json:"group_by,omitempty"`
	DistinctGroupBy []string `protobuf:"bytes,7,rep,name=distinct_group_by,json=distinctGroupBy" json:"distinct_group_by,omitempty"`
	// Field to sort by.
	SortBy string `protobuf:"bytes,8,opt,name=sort_by,json=sortBy" json:"sort_by,omitempty"`
	// Column to consider as the time column.
	TimeColumn string `protobuf:"bytes,9,opt,name=time_column,json=timeColumn" json:"time_column,omitempty"`
	// Time bucket size in seconds.
	TimeBucket int64 `protobuf:"varint,10,opt,name=time_bucket,json=timeBucket" json:"time_bucket,omitempty"`
	// The column to interpret as the weight.
	WeightColumn string `protobuf:"bytes,11,opt,name=weight_column,json=weightColumn" json:"weight_column,omitempty"`
	// The operation to run.
	Op QueryOp `protobuf:"varint,12,opt,name=op,enum=pb.QueryOp" json:"op,omitempty"`
	// Filters on int columns.
	IntFilters []*QueryFilter `protobuf:"bytes,13,rep,name=int_filters,json=intFilters" json:"int_filters,omitempty"`
	// Filters on string columns.
	StrFilters []*QueryFilter `protobuf:"bytes,14,rep,name=str_filters,json=strFilters" json:"str_filters,omitempty"`
	// Filters on set columns.
	SetFilters []*QueryFilter `protobuf:"bytes,15,rep,name=set_filters,json=setFilters" json:"set_filters,omitempty"`
	// If type is DISTRIBUTION then this field controls hisogram options.
	HistogramOptions *HistogramOptions `protobuf:"bytes,16,opt,name=histogram_options,json=histogramOptions" json:"histogram_options,omitempty"`
	// If true, the ingestion log is also read to produce results.
	ReadIngestionLog bool `protobuf:"varint,17,opt,name=read_ingestion_log,json=readIngestionLog" json:"read_ingestion_log,omitempty"`
}

func (m *QueryRequest) Reset()                    { *m = QueryRequest{} }
func (m *QueryRequest) String() string            { return proto.CompactTextString(m) }
func (*QueryRequest) ProtoMessage()               {}
func (*QueryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *QueryRequest) GetDataset() string {
	if m != nil {
		return m.Dataset
	}
	return ""
}

func (m *QueryRequest) GetType() QueryType {
	if m != nil {
		return m.Type
	}
	return QueryType_QUERY_TYPE_UNKNOWN
}

func (m *QueryRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *QueryRequest) GetInts() []string {
	if m != nil {
		return m.Ints
	}
	return nil
}

func (m *QueryRequest) GetStrs() []string {
	if m != nil {
		return m.Strs
	}
	return nil
}

func (m *QueryRequest) GetGroupBy() []string {
	if m != nil {
		return m.GroupBy
	}
	return nil
}

func (m *QueryRequest) GetDistinctGroupBy() []string {
	if m != nil {
		return m.DistinctGroupBy
	}
	return nil
}

func (m *QueryRequest) GetSortBy() string {
	if m != nil {
		return m.SortBy
	}
	return ""
}

func (m *QueryRequest) GetTimeColumn() string {
	if m != nil {
		return m.TimeColumn
	}
	return ""
}

func (m *QueryRequest) GetTimeBucket() int64 {
	if m != nil {
		return m.TimeBucket
	}
	return 0
}

func (m *QueryRequest) GetWeightColumn() string {
	if m != nil {
		return m.WeightColumn
	}
	return ""
}

func (m *QueryRequest) GetOp() QueryOp {
	if m != nil {
		return m.Op
	}
	return QueryOp_QUERY_OP_UNKNOWN
}

func (m *QueryRequest) GetIntFilters() []*QueryFilter {
	if m != nil {
		return m.IntFilters
	}
	return nil
}

func (m *QueryRequest) GetStrFilters() []*QueryFilter {
	if m != nil {
		return m.StrFilters
	}
	return nil
}

func (m *QueryRequest) GetSetFilters() []*QueryFilter {
	if m != nil {
		return m.SetFilters
	}
	return nil
}

func (m *QueryRequest) GetHistogramOptions() *HistogramOptions {
	if m != nil {
		return m.HistogramOptions
	}
	return nil
}

func (m *QueryRequest) GetReadIngestionLog() bool {
	if m != nil {
		return m.ReadIngestionLog
	}
	return false
}

// HistogramOptions
type HistogramOptions struct {
	Type       HistogramType `protobuf:"varint,1,opt,name=type,enum=pb.HistogramType" json:"type,omitempty"`
	BucketSize int64         `protobuf:"varint,2,opt,name=bucket_size,json=bucketSize" json:"bucket_size,omitempty"`
}

func (m *HistogramOptions) Reset()                    { *m = HistogramOptions{} }
func (m *HistogramOptions) String() string            { return proto.CompactTextString(m) }
func (*HistogramOptions) ProtoMessage()               {}
func (*HistogramOptions) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *HistogramOptions) GetType() HistogramType {
	if m != nil {
		return m.Type
	}
	return HistogramType_HISTOGRAM_TYPE_UNKNOWN
}

func (m *HistogramOptions) GetBucketSize() int64 {
	if m != nil {
		return m.BucketSize
	}
	return 0
}

// Histogram describes a distribution of values.
type Histogram struct {
	Mean         float64 `protobuf:"fixed64,1,opt,name=mean" json:"mean,omitempty"`
	Percentiles  []int64 `protobuf:"varint,5,rep,packed,name=percentiles" json:"percentiles,omitempty"`
	Buckets      []int64 `protobuf:"varint,6,rep,packed,name=buckets" json:"buckets,omitempty"`
	StdDeviation float64 `protobuf:"fixed64,9,opt,name=std_deviation,json=stdDeviation" json:"std_deviation,omitempty"`
}

func (m *Histogram) Reset()                    { *m = Histogram{} }
func (m *Histogram) String() string            { return proto.CompactTextString(m) }
func (*Histogram) ProtoMessage()               {}
func (*Histogram) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Histogram) GetMean() float64 {
	if m != nil {
		return m.Mean
	}
	return 0
}

func (m *Histogram) GetPercentiles() []int64 {
	if m != nil {
		return m.Percentiles
	}
	return nil
}

func (m *Histogram) GetBuckets() []int64 {
	if m != nil {
		return m.Buckets
	}
	return nil
}

func (m *Histogram) GetStdDeviation() float64 {
	if m != nil {
		return m.StdDeviation
	}
	return 0
}

// ResultMap
type ResultMap struct {
	Values map[string]*QueryResult `protobuf:"bytes,1,rep,name=values" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *ResultMap) Reset()                    { *m = ResultMap{} }
func (m *ResultMap) String() string            { return proto.CompactTextString(m) }
func (*ResultMap) ProtoMessage()               {}
func (*ResultMap) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ResultMap) GetValues() map[string]*QueryResult {
	if m != nil {
		return m.Values
	}
	return nil
}

// SetField
type SetField struct {
	Values []string `protobuf:"bytes,1,rep,name=values" json:"values,omitempty"`
}

func (m *SetField) Reset()                    { *m = SetField{} }
func (m *SetField) String() string            { return proto.CompactTextString(m) }
func (*SetField) ProtoMessage()               {}
func (*SetField) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *SetField) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

// Record is an individual record.
type Record struct {
	Strs map[string]string    `protobuf:"bytes,1,rep,name=strs" json:"strs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Ints map[string]int64     `protobuf:"bytes,2,rep,name=ints" json:"ints,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Sets map[string]*SetField `protobuf:"bytes,3,rep,name=sets" json:"sets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Record) Reset()                    { *m = Record{} }
func (m *Record) String() string            { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()               {}
func (*Record) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Record) GetStrs() map[string]string {
	if m != nil {
		return m.Strs
	}
	return nil
}

func (m *Record) GetInts() map[string]int64 {
	if m != nil {
		return m.Ints
	}
	return nil
}

func (m *Record) GetSets() map[string]*SetField {
	if m != nil {
		return m.Sets
	}
	return nil
}

type FieldValue struct {
	// Types that are valid to be assigned to Value:
	//	*FieldValue_Avg
	//	*FieldValue_Hist
	//	*FieldValue_Str
	Value isFieldValue_Value `protobuf_oneof:"value"`
}

func (m *FieldValue) Reset()                    { *m = FieldValue{} }
func (m *FieldValue) String() string            { return proto.CompactTextString(m) }
func (*FieldValue) ProtoMessage()               {}
func (*FieldValue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type isFieldValue_Value interface {
	isFieldValue_Value()
}

type FieldValue_Avg struct {
	Avg float64 `protobuf:"fixed64,1,opt,name=avg,oneof"`
}
type FieldValue_Hist struct {
	Hist *Histogram `protobuf:"bytes,2,opt,name=hist,oneof"`
}
type FieldValue_Str struct {
	Str string `protobuf:"bytes,3,opt,name=str,oneof"`
}

func (*FieldValue_Avg) isFieldValue_Value()  {}
func (*FieldValue_Hist) isFieldValue_Value() {}
func (*FieldValue_Str) isFieldValue_Value()  {}

func (m *FieldValue) GetValue() isFieldValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *FieldValue) GetAvg() float64 {
	if x, ok := m.GetValue().(*FieldValue_Avg); ok {
		return x.Avg
	}
	return 0
}

func (m *FieldValue) GetHist() *Histogram {
	if x, ok := m.GetValue().(*FieldValue_Hist); ok {
		return x.Hist
	}
	return nil
}

func (m *FieldValue) GetStr() string {
	if x, ok := m.GetValue().(*FieldValue_Str); ok {
		return x.Str
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*FieldValue) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _FieldValue_OneofMarshaler, _FieldValue_OneofUnmarshaler, _FieldValue_OneofSizer, []interface{}{
		(*FieldValue_Avg)(nil),
		(*FieldValue_Hist)(nil),
		(*FieldValue_Str)(nil),
	}
}

func _FieldValue_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*FieldValue)
	// value
	switch x := m.Value.(type) {
	case *FieldValue_Avg:
		b.EncodeVarint(1<<3 | proto.WireFixed64)
		b.EncodeFixed64(math.Float64bits(x.Avg))
	case *FieldValue_Hist:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Hist); err != nil {
			return err
		}
	case *FieldValue_Str:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Str)
	case nil:
	default:
		return fmt.Errorf("FieldValue.Value has unexpected type %T", x)
	}
	return nil
}

func _FieldValue_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*FieldValue)
	switch tag {
	case 1: // value.avg
		if wire != proto.WireFixed64 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed64()
		m.Value = &FieldValue_Avg{math.Float64frombits(x)}
		return true, err
	case 2: // value.hist
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Histogram)
		err := b.DecodeMessage(msg)
		m.Value = &FieldValue_Hist{msg}
		return true, err
	case 3: // value.str
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Value = &FieldValue_Str{x}
		return true, err
	default:
		return false, nil
	}
}

func _FieldValue_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*FieldValue)
	// value
	switch x := m.Value.(type) {
	case *FieldValue_Avg:
		n += proto.SizeVarint(1<<3 | proto.WireFixed64)
		n += 8
	case *FieldValue_Hist:
		s := proto.Size(x.Hist)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *FieldValue_Str:
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Str)))
		n += len(x.Str)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type QueryResult struct {
	Values   map[string]*FieldValue `protobuf:"bytes,1,rep,name=values" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Count    int64                  `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
	Samples  int64                  `protobuf:"varint,3,opt,name=samples" json:"samples,omitempty"`
	Distinct int64                  `protobuf:"varint,4,opt,name=distinct" json:"distinct,omitempty"`
	// if a time-series query, the time bucket for the result.
	Time int64 `protobuf:"varint,5,opt,name=time" json:"time,omitempty"`
}

func (m *QueryResult) Reset()                    { *m = QueryResult{} }
func (m *QueryResult) String() string            { return proto.CompactTextString(m) }
func (*QueryResult) ProtoMessage()               {}
func (*QueryResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *QueryResult) GetValues() map[string]*FieldValue {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *QueryResult) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *QueryResult) GetSamples() int64 {
	if m != nil {
		return m.Samples
	}
	return 0
}

func (m *QueryResult) GetDistinct() int64 {
	if m != nil {
		return m.Distinct
	}
	return 0
}

func (m *QueryResult) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

// QueryResponse is the response type for a query.
type QueryResponse struct {
	Results    []*QueryResult `protobuf:"bytes,1,rep,name=results" json:"results,omitempty"`
	Cumulative *QueryResult   `protobuf:"bytes,2,opt,name=cumulative" json:"cumulative,omitempty"`
	Samples    []*Record      `protobuf:"bytes,3,rep,name=samples" json:"samples,omitempty"`
}

func (m *QueryResponse) Reset()                    { *m = QueryResponse{} }
func (m *QueryResponse) String() string            { return proto.CompactTextString(m) }
func (*QueryResponse) ProtoMessage()               {}
func (*QueryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *QueryResponse) GetResults() []*QueryResult {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *QueryResponse) GetCumulative() *QueryResult {
	if m != nil {
		return m.Cumulative
	}
	return nil
}

func (m *QueryResponse) GetSamples() []*Record {
	if m != nil {
		return m.Samples
	}
	return nil
}

// ListTablesRequest requests the list of tables from sybil.
type ListTablesRequest struct {
}

func (m *ListTablesRequest) Reset()                    { *m = ListTablesRequest{} }
func (m *ListTablesRequest) String() string            { return proto.CompactTextString(m) }
func (*ListTablesRequest) ProtoMessage()               {}
func (*ListTablesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

// ListTablesResponse contains the list of tables in sybil.
type ListTablesResponse struct {
	Tables []string `protobuf:"bytes,1,rep,name=tables" json:"tables,omitempty"`
}

func (m *ListTablesResponse) Reset()                    { *m = ListTablesResponse{} }
func (m *ListTablesResponse) String() string            { return proto.CompactTextString(m) }
func (*ListTablesResponse) ProtoMessage()               {}
func (*ListTablesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *ListTablesResponse) GetTables() []string {
	if m != nil {
		return m.Tables
	}
	return nil
}

// GetTableRequest requests details about a table.
type GetTableRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *GetTableRequest) Reset()                    { *m = GetTableRequest{} }
func (m *GetTableRequest) String() string            { return proto.CompactTextString(m) }
func (*GetTableRequest) ProtoMessage()               {}
func (*GetTableRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *GetTableRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// Table (aka dataset) is a collection of records in a sybil database.
type Table struct {
	// the name of the dataset.
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// the set of string column names.
	StrColumns []string `protobuf:"bytes,2,rep,name=str_columns,json=strColumns" json:"str_columns,omitempty"`
	// the set of integer column names.
	IntColumns []string `protobuf:"bytes,3,rep,name=int_columns,json=intColumns" json:"int_columns,omitempty"`
	// the set of set column names.
	SetColumns []string `protobuf:"bytes,4,rep,name=set_columns,json=setColumns" json:"set_columns,omitempty"`
	// the approximate count of samples.
	Count int64 `protobuf:"varint,5,opt,name=count" json:"count,omitempty"`
	// the approximate size in terms of disk utilization.
	StorageSize int64 `protobuf:"varint,6,opt,name=storage_size,json=storageSize" json:"storage_size,omitempty"`
	// the mean sample storage size.
	AverageObjectSize float64 `protobuf:"fixed64,7,opt,name=average_object_size,json=averageObjectSize" json:"average_object_size,omitempty"`
}

func (m *Table) Reset()                    { *m = Table{} }
func (m *Table) String() string            { return proto.CompactTextString(m) }
func (*Table) ProtoMessage()               {}
func (*Table) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *Table) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Table) GetStrColumns() []string {
	if m != nil {
		return m.StrColumns
	}
	return nil
}

func (m *Table) GetIntColumns() []string {
	if m != nil {
		return m.IntColumns
	}
	return nil
}

func (m *Table) GetSetColumns() []string {
	if m != nil {
		return m.SetColumns
	}
	return nil
}

func (m *Table) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *Table) GetStorageSize() int64 {
	if m != nil {
		return m.StorageSize
	}
	return 0
}

func (m *Table) GetAverageObjectSize() float64 {
	if m != nil {
		return m.AverageObjectSize
	}
	return 0
}

// TrimRequest queries and optionally removes data from a dataset.
type TrimRequest struct {
	// The name of the dataset.
	Dataset string `protobuf:"bytes,1,opt,name=dataset" json:"dataset,omitempty"`
	// The column to interpret as the time column.
	TimeColumn string `protobuf:"bytes,2,opt,name=time_column,json=timeColumn" json:"time_column,omitempty"`
	// Limit, in megabytes, for the dataset.
	SizeLimitMb int64 `protobuf:"varint,3,opt,name=size_limit_mb,json=sizeLimitMb" json:"size_limit_mb,omitempty"`
	// Limit, in the form a timestamp for the dataset.
	TimeLimit int64 `protobuf:"varint,4,opt,name=time_limit,json=timeLimit" json:"time_limit,omitempty"`
	Delete    bool  `protobuf:"varint,5,opt,name=delete" json:"delete,omitempty"`
}

func (m *TrimRequest) Reset()                    { *m = TrimRequest{} }
func (m *TrimRequest) String() string            { return proto.CompactTextString(m) }
func (*TrimRequest) ProtoMessage()               {}
func (*TrimRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *TrimRequest) GetDataset() string {
	if m != nil {
		return m.Dataset
	}
	return ""
}

func (m *TrimRequest) GetTimeColumn() string {
	if m != nil {
		return m.TimeColumn
	}
	return ""
}

func (m *TrimRequest) GetSizeLimitMb() int64 {
	if m != nil {
		return m.SizeLimitMb
	}
	return 0
}

func (m *TrimRequest) GetTimeLimit() int64 {
	if m != nil {
		return m.TimeLimit
	}
	return 0
}

func (m *TrimRequest) GetDelete() bool {
	if m != nil {
		return m.Delete
	}
	return false
}

// TrimResponse returns the number of blocks matched by the provided thresholds.
type TrimResponse struct {
	// The number of blocks that matched the trim request.
	MatchedBlocks int64 `protobuf:"varint,1,opt,name=matched_blocks,json=matchedBlocks" json:"matched_blocks,omitempty"`
	// Data older than this timestamp matched the trim request. If this doesn't match the provided 'time_limit' then the 'size_limit_mb' field threshold was lower than the 'time_limit' threshold.
	TrimmedAt int64 `protobuf:"varint,2,opt,name=trimmed_at,json=trimmedAt" json:"trimmed_at,omitempty"`
}

func (m *TrimResponse) Reset()                    { *m = TrimResponse{} }
func (m *TrimResponse) String() string            { return proto.CompactTextString(m) }
func (*TrimResponse) ProtoMessage()               {}
func (*TrimResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *TrimResponse) GetMatchedBlocks() int64 {
	if m != nil {
		return m.MatchedBlocks
	}
	return 0
}

func (m *TrimResponse) GetTrimmedAt() int64 {
	if m != nil {
		return m.TrimmedAt
	}
	return 0
}

func init() {
	proto.RegisterType((*IngestRequest)(nil), "pb.IngestRequest")
	proto.RegisterType((*IngestResponse)(nil), "pb.IngestResponse")
	proto.RegisterType((*QueryFilter)(nil), "pb.QueryFilter")
	proto.RegisterType((*QueryRequest)(nil), "pb.QueryRequest")
	proto.RegisterType((*HistogramOptions)(nil), "pb.HistogramOptions")
	proto.RegisterType((*Histogram)(nil), "pb.Histogram")
	proto.RegisterType((*ResultMap)(nil), "pb.ResultMap")
	proto.RegisterType((*SetField)(nil), "pb.SetField")
	proto.RegisterType((*Record)(nil), "pb.Record")
	proto.RegisterType((*FieldValue)(nil), "pb.FieldValue")
	proto.RegisterType((*QueryResult)(nil), "pb.QueryResult")
	proto.RegisterType((*QueryResponse)(nil), "pb.QueryResponse")
	proto.RegisterType((*ListTablesRequest)(nil), "pb.ListTablesRequest")
	proto.RegisterType((*ListTablesResponse)(nil), "pb.ListTablesResponse")
	proto.RegisterType((*GetTableRequest)(nil), "pb.GetTableRequest")
	proto.RegisterType((*Table)(nil), "pb.Table")
	proto.RegisterType((*TrimRequest)(nil), "pb.TrimRequest")
	proto.RegisterType((*TrimResponse)(nil), "pb.TrimResponse")
	proto.RegisterEnum("pb.QueryType", QueryType_name, QueryType_value)
	proto.RegisterEnum("pb.QueryOp", QueryOp_name, QueryOp_value)
	proto.RegisterEnum("pb.QueryFilterOp", QueryFilterOp_name, QueryFilterOp_value)
	proto.RegisterEnum("pb.HistogramType", HistogramType_name, HistogramType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Sybil service

type SybilClient interface {
	// Ingest inserts new data into a sybil dataset.
	Ingest(ctx context.Context, in *IngestRequest, opts ...grpc.CallOption) (*IngestResponse, error)
	// Query retrieves results from sybil.
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	// ListTables lists the tables in a sybil database.
	ListTables(ctx context.Context, in *ListTablesRequest, opts ...grpc.CallOption) (*ListTablesResponse, error)
	// GetTable gets details about a particular table.
	GetTable(ctx context.Context, in *GetTableRequest, opts ...grpc.CallOption) (*Table, error)
	// Trim lists and possily removes data exceeding some thresholds.
	Trim(ctx context.Context, in *TrimRequest, opts ...grpc.CallOption) (*TrimResponse, error)
}

type sybilClient struct {
	cc *grpc.ClientConn
}

func NewSybilClient(cc *grpc.ClientConn) SybilClient {
	return &sybilClient{cc}
}

func (c *sybilClient) Ingest(ctx context.Context, in *IngestRequest, opts ...grpc.CallOption) (*IngestResponse, error) {
	out := new(IngestResponse)
	err := grpc.Invoke(ctx, "/pb.Sybil/Ingest", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sybilClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	out := new(QueryResponse)
	err := grpc.Invoke(ctx, "/pb.Sybil/Query", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sybilClient) ListTables(ctx context.Context, in *ListTablesRequest, opts ...grpc.CallOption) (*ListTablesResponse, error) {
	out := new(ListTablesResponse)
	err := grpc.Invoke(ctx, "/pb.Sybil/ListTables", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sybilClient) GetTable(ctx context.Context, in *GetTableRequest, opts ...grpc.CallOption) (*Table, error) {
	out := new(Table)
	err := grpc.Invoke(ctx, "/pb.Sybil/GetTable", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sybilClient) Trim(ctx context.Context, in *TrimRequest, opts ...grpc.CallOption) (*TrimResponse, error) {
	out := new(TrimResponse)
	err := grpc.Invoke(ctx, "/pb.Sybil/Trim", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Sybil service

type SybilServer interface {
	// Ingest inserts new data into a sybil dataset.
	Ingest(context.Context, *IngestRequest) (*IngestResponse, error)
	// Query retrieves results from sybil.
	Query(context.Context, *QueryRequest) (*QueryResponse, error)
	// ListTables lists the tables in a sybil database.
	ListTables(context.Context, *ListTablesRequest) (*ListTablesResponse, error)
	// GetTable gets details about a particular table.
	GetTable(context.Context, *GetTableRequest) (*Table, error)
	// Trim lists and possily removes data exceeding some thresholds.
	Trim(context.Context, *TrimRequest) (*TrimResponse, error)
}

func RegisterSybilServer(s *grpc.Server, srv SybilServer) {
	s.RegisterService(&_Sybil_serviceDesc, srv)
}

func _Sybil_Ingest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SybilServer).Ingest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Sybil/Ingest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SybilServer).Ingest(ctx, req.(*IngestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sybil_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SybilServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Sybil/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SybilServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sybil_ListTables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SybilServer).ListTables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Sybil/ListTables",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SybilServer).ListTables(ctx, req.(*ListTablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sybil_GetTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SybilServer).GetTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Sybil/GetTable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SybilServer).GetTable(ctx, req.(*GetTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sybil_Trim_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrimRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SybilServer).Trim(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Sybil/Trim",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SybilServer).Trim(ctx, req.(*TrimRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Sybil_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Sybil",
	HandlerType: (*SybilServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ingest",
			Handler:    _Sybil_Ingest_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _Sybil_Query_Handler,
		},
		{
			MethodName: "ListTables",
			Handler:    _Sybil_ListTables_Handler,
		},
		{
			MethodName: "GetTable",
			Handler:    _Sybil_GetTable_Handler,
		},
		{
			MethodName: "Trim",
			Handler:    _Sybil_Trim_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sybild.proto",
}

func init() { proto.RegisterFile("sybild.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1521 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x57, 0xdd, 0x72, 0xdb, 0x44,
	0x14, 0x8e, 0x24, 0xff, 0xe9, 0xc8, 0x4e, 0xe4, 0x6d, 0x48, 0x5d, 0x77, 0x98, 0xa6, 0x6a, 0x33,
	0x98, 0xd0, 0x71, 0x68, 0x3a, 0x0c, 0x7f, 0xc3, 0x85, 0x43, 0xdd, 0xc4, 0xe0, 0xd8, 0xcd, 0xda,
	0x2d, 0x53, 0x86, 0xa9, 0x46, 0xb6, 0xb7, 0x8e, 0xa8, 0x2d, 0x09, 0xed, 0x3a, 0x8c, 0x7b, 0xc5,
	0x05, 0x57, 0xdc, 0xf1, 0x0c, 0x3c, 0x08, 0x8f, 0xc3, 0x15, 0x77, 0x3c, 0x00, 0xb3, 0x3f, 0x92,
	0x15, 0x27, 0x9d, 0x5c, 0x59, 0xfb, 0x9d, 0xef, 0x9c, 0xdd, 0x3d, 0xbf, 0x6b, 0x28, 0xd3, 0xe5,
	0xc8, 0x9f, 0x4d, 0x9a, 0x51, 0x1c, 0xb2, 0x10, 0xe9, 0xd1, 0xa8, 0xfe, 0xd9, 0xd4, 0x67, 0xe7,
	0x8b, 0x51, 0x73, 0x1c, 0xce, 0x0f, 0xa6, 0xe1, 0xcc, 0x0b, 0xa6, 0x07, 0x42, 0x38, 0x5a, 0xbc,
	0x39, 0x88, 0xd8, 0x32, 0x22, 0xf4, 0x80, 0xb2, 0x78, 0x31, 0x66, 0xea, 0x47, 0xaa, 0x3a, 0x3f,
	0x41, 0xa5, 0x13, 0x4c, 0x09, 0x65, 0x98, 0xfc, 0xb2, 0x20, 0x94, 0xa1, 0x1a, 0x14, 0x27, 0x1e,
	0xf3, 0x28, 0x61, 0x35, 0x6d, 0x57, 0x6b, 0x98, 0x38, 0x59, 0xa2, 0xc7, 0x50, 0x8c, 0xc9, 0x38,
	0x8c, 0x27, 0xb4, 0xa6, 0xef, 0x1a, 0x0d, 0xeb, 0xf0, 0x76, 0x73, 0x1a, 0x86, 0xd3, 0x19, 0x69,
	0x26, 0x1b, 0x35, 0x07, 0xc2, 0x34, 0x4e, 0x78, 0xce, 0x97, 0xb0, 0x99, 0x58, 0xa7, 0x51, 0x18,
	0x50, 0x82, 0x3e, 0x82, 0xad, 0x60, 0x31, 0x1f, 0x91, 0xd8, 0xf5, 0x03, 0x4a, 0x62, 0x46, 0x26,
	0x62, 0x1b, 0x03, 0x6f, 0x4a, 0xb8, 0xa3, 0x50, 0xe7, 0x35, 0x58, 0x67, 0x0b, 0x12, 0x2f, 0x9f,
	0xf9, 0x33, 0x46, 0x62, 0xb4, 0x03, 0x85, 0x71, 0x38, 0x5b, 0xcc, 0x03, 0x75, 0x2a, 0xb5, 0x42,
	0xf7, 0x41, 0x0f, 0xa3, 0x9a, 0xbe, 0xab, 0x35, 0x36, 0x0f, 0xab, 0xcd, 0x68, 0xd4, 0xcc, 0x28,
	0xf5, 0x23, 0xac, 0x87, 0x11, 0xda, 0x86, 0xfc, 0x85, 0x37, 0x5b, 0x90, 0x9a, 0x21, 0x34, 0xe5,
	0xc2, 0xf9, 0x2f, 0x07, 0x65, 0xc1, 0xbd, 0xf9, 0xe2, 0xf7, 0x21, 0xc7, 0x1d, 0xa8, 0x76, 0xa9,
	0xa4, 0xbb, 0x0c, 0x97, 0x11, 0xc1, 0x42, 0xc4, 0xf7, 0x98, 0xf9, 0x73, 0x9f, 0x89, 0x3d, 0x0c,
	0x2c, 0x17, 0x08, 0x41, 0xce, 0x0f, 0x18, 0xad, 0xe5, 0x76, 0x8d, 0x86, 0x89, 0xc5, 0x37, 0xc7,
	0x28, 0x8b, 0x69, 0x2d, 0x2f, 0x31, 0xfe, 0x8d, 0xee, 0x40, 0x69, 0x1a, 0x87, 0x8b, 0xc8, 0x1d,
	0x2d, 0x6b, 0x05, 0x81, 0x17, 0xc5, 0xfa, 0x68, 0x89, 0xf6, 0xa1, 0x3a, 0xf1, 0x29, 0xf3, 0x83,
	0x31, 0x73, 0x53, 0x4e, 0x51, 0x70, 0xb6, 0x12, 0xc1, 0xb1, 0xe2, 0xde, 0x86, 0x22, 0x0d, 0x63,
	0xc6, 0x19, 0x25, 0xe9, 0x24, 0xbe, 0x3c, 0x5a, 0xa2, 0x7b, 0x60, 0x31, 0x7f, 0x4e, 0x5c, 0xe5,
	0x41, 0x53, 0x08, 0x81, 0x43, 0xdf, 0x4a, 0x2f, 0x26, 0x84, 0xd1, 0x62, 0xfc, 0x96, 0xb0, 0x1a,
	0x88, 0x4b, 0x08, 0xc2, 0x91, 0x40, 0xd0, 0x03, 0xa8, 0xfc, 0x4a, 0xfc, 0xe9, 0x39, 0x4b, 0x6c,
	0x58, 0xc2, 0x46, 0x59, 0x82, 0xca, 0xca, 0x5d, 0x11, 0x8b, 0xb2, 0xf0, 0x92, 0x95, 0x7a, 0x49,
	0x45, 0xe1, 0x53, 0xb0, 0xfc, 0x80, 0xb9, 0x6f, 0x44, 0x64, 0x68, 0xad, 0x22, 0x32, 0x68, 0x6b,
	0x2d, 0x62, 0x18, 0xfc, 0x80, 0xc9, 0x4f, 0xca, 0x35, 0x28, 0x8b, 0x53, 0x8d, 0xcd, 0xf7, 0x68,
	0x50, 0x16, 0x67, 0x35, 0xc8, 0x6a, 0x8f, 0xad, 0xf7, 0x69, 0x90, 0x74, 0x8f, 0x16, 0x54, 0xcf,
	0x7d, 0xca, 0xc2, 0x69, 0xec, 0xcd, 0xdd, 0x30, 0x62, 0x7e, 0x18, 0xd0, 0x9a, 0xbd, 0xab, 0x35,
	0xac, 0xc3, 0x6d, 0xae, 0x77, 0x92, 0x08, 0xfb, 0x52, 0x86, 0xed, 0xf3, 0x35, 0x04, 0x3d, 0x02,
	0x14, 0x13, 0x6f, 0xe2, 0xfa, 0x22, 0xd1, 0xfd, 0x30, 0x70, 0x67, 0xe1, 0xb4, 0x56, 0xdd, 0xd5,
	0x1a, 0x25, 0x6c, 0x73, 0x49, 0x27, 0x11, 0x74, 0xc3, 0xa9, 0xf3, 0x23, 0xd8, 0xeb, 0x36, 0xd1,
	0x9e, 0xca, 0x2f, 0x6d, 0x95, 0xc5, 0x29, 0x27, 0x93, 0x63, 0xf7, 0xc0, 0x92, 0xf1, 0x71, 0xa9,
	0xff, 0x4e, 0x66, 0xa3, 0x81, 0x41, 0x42, 0x03, 0xff, 0x1d, 0x71, 0x7e, 0xd3, 0xc0, 0x4c, 0x15,
	0x79, 0xa2, 0xcd, 0x89, 0x27, 0xeb, 0x45, 0xc3, 0xe2, 0x1b, 0xed, 0x82, 0x15, 0x91, 0x78, 0x4c,
	0x02, 0xe6, 0xcf, 0x88, 0xcc, 0x41, 0x03, 0x67, 0x21, 0x5e, 0x05, 0xd2, 0x22, 0x15, 0x99, 0x68,
	0xe0, 0x64, 0xc9, 0x53, 0x80, 0xb2, 0x89, 0x3b, 0x21, 0x17, 0xbe, 0xc7, 0xcf, 0x2d, 0xd2, 0x48,
	0xc3, 0x65, 0xca, 0x26, 0x4f, 0x13, 0xcc, 0xf9, 0x43, 0x03, 0x13, 0x13, 0xba, 0x98, 0xb1, 0x53,
	0x2f, 0x42, 0x8f, 0xa1, 0x20, 0x8a, 0x8d, 0xd6, 0x34, 0x11, 0x8a, 0x3b, 0xfc, 0x6a, 0xa9, 0xb8,
	0xf9, 0x52, 0xc8, 0xda, 0x01, 0x8b, 0x97, 0x58, 0x11, 0xeb, 0xdf, 0x81, 0x95, 0x81, 0x91, 0x0d,
	0xc6, 0x5b, 0xb2, 0x54, 0x05, 0xc9, 0x3f, 0xd1, 0x5e, 0x52, 0xcd, 0xba, 0x88, 0xd2, 0x2a, 0xba,
	0xd2, 0xae, 0x2a, 0xef, 0xaf, 0xf4, 0x2f, 0x34, 0xc7, 0x81, 0xd2, 0x80, 0x87, 0x9a, 0xcc, 0x26,
	0xbc, 0x7f, 0x64, 0x8e, 0x62, 0x26, 0xfb, 0x39, 0x7f, 0xeb, 0x50, 0xc0, 0xa2, 0x5b, 0xa1, 0x86,
	0xaa, 0x4c, 0x79, 0xd6, 0x6d, 0x79, 0x56, 0x2e, 0xe1, 0x6d, 0x4d, 0x1d, 0x53, 0xd6, 0x6b, 0x43,
	0xd5, 0xb5, 0x7e, 0x85, 0xd9, 0x09, 0x58, 0xc2, 0x14, 0xd5, 0xce, 0x6d, 0x72, 0x5f, 0x1a, 0x57,
	0x6d, 0x92, 0x94, 0xc9, 0x19, 0xf5, 0xcf, 0xc1, 0x4c, 0xb7, 0xb9, 0xe6, 0xda, 0xdb, 0xd9, 0x6b,
	0x9b, 0x99, 0x5b, 0x72, 0xc5, 0x74, 0xd7, 0x9b, 0x14, 0x8d, 0xac, 0x62, 0x1b, 0xcc, 0xf4, 0x10,
	0xd7, 0x28, 0x3a, 0x97, 0x1d, 0x5d, 0xe6, 0x67, 0x4f, 0xdc, 0x99, 0xf5, 0xf2, 0x08, 0x40, 0x60,
	0x22, 0x6c, 0x08, 0x81, 0xe1, 0x5d, 0x4c, 0x65, 0xd2, 0x9d, 0x6c, 0x60, 0xbe, 0x40, 0x0f, 0x20,
	0xc7, 0xab, 0x46, 0x19, 0xaa, 0x5c, 0xca, 0xef, 0x93, 0x0d, 0x2c, 0x84, 0x5c, 0x91, 0xb2, 0x58,
	0xf6, 0x68, 0xae, 0x48, 0x59, 0x7c, 0x54, 0x54, 0x47, 0x70, 0xfe, 0xd5, 0xd4, 0x34, 0x90, 0x41,
	0x46, 0x4f, 0xd6, 0x12, 0xeb, 0xee, 0x5a, 0x16, 0x5c, 0x97, 0x5a, 0xdc, 0x13, 0xe3, 0x70, 0x11,
	0xb0, 0xc4, 0x13, 0x62, 0xc1, 0x13, 0x9e, 0x7a, 0xf3, 0x88, 0x97, 0x83, 0xec, 0xdd, 0xc9, 0x12,
	0xd5, 0xa1, 0x94, 0x74, 0xd8, 0x5a, 0x4e, 0x88, 0xd2, 0x35, 0x2f, 0x2e, 0xde, 0x1d, 0x6b, 0x79,
	0x81, 0x8b, 0xef, 0x7a, 0xe7, 0xa6, 0xd4, 0x7d, 0x78, 0xd9, 0xa3, 0x9b, 0xfc, 0xd0, 0x2b, 0xd7,
	0x65, 0x7d, 0xfa, 0xa7, 0x06, 0x95, 0xe4, 0x3a, 0x72, 0x6e, 0x7e, 0xcc, 0x87, 0x2f, 0xbf, 0x5a,
	0x72, 0xe5, 0x2b, 0x89, 0x9f, 0xc8, 0xd1, 0x01, 0xc0, 0x78, 0x31, 0x5f, 0xcc, 0x3c, 0xe6, 0x5f,
	0xbc, 0xb7, 0x4c, 0x32, 0x14, 0xf4, 0x30, 0xeb, 0x02, 0x6e, 0x1b, 0x56, 0x79, 0x9a, 0xba, 0xc3,
	0xb9, 0x05, 0xd5, 0xae, 0x4f, 0xd9, 0xd0, 0x1b, 0xcd, 0x08, 0x55, 0x43, 0xd3, 0x79, 0x04, 0x28,
	0x0b, 0xaa, 0xc3, 0xee, 0x40, 0x81, 0x09, 0x24, 0x29, 0x36, 0xb9, 0x72, 0xf6, 0x60, 0xeb, 0x98,
	0x48, 0x72, 0x32, 0x75, 0x11, 0xe4, 0x02, 0x6f, 0x4e, 0x94, 0x9b, 0xc4, 0xb7, 0xf3, 0x8f, 0x06,
	0x79, 0x41, 0xba, 0x4e, 0xca, 0xdb, 0x20, 0x1f, 0x0b, 0x72, 0x0e, 0xc9, 0x1a, 0x34, 0xc5, 0x14,
	0x90, 0x53, 0x88, 0x72, 0x02, 0x9f, 0x34, 0x09, 0xc1, 0x90, 0x04, 0x3f, 0x60, 0x19, 0x02, 0x1f,
	0x13, 0x09, 0x21, 0xa7, 0x2c, 0x90, 0x94, 0x90, 0x66, 0x4a, 0x3e, 0x9b, 0x29, 0xf7, 0xa1, 0x4c,
	0x59, 0x18, 0x7b, 0x53, 0x22, 0x1b, 0x70, 0x41, 0x08, 0x2d, 0x85, 0xf1, 0x0e, 0x8c, 0x9a, 0x70,
	0xcb, 0xbb, 0x20, 0x82, 0x12, 0x8e, 0x7e, 0x26, 0x63, 0xd5, 0xaa, 0x8b, 0xa2, 0x53, 0x56, 0x95,
	0xa8, 0x2f, 0x24, 0xa2, 0x63, 0xff, 0xa5, 0x81, 0x35, 0x8c, 0xfd, 0xf9, 0xcd, 0x6f, 0x90, 0xb5,
	0x11, 0xae, 0x5f, 0x19, 0xe1, 0x0e, 0x54, 0xf8, 0x5e, 0xae, 0x78, 0x79, 0xb8, 0xf3, 0x91, 0xca,
	0x66, 0x8b, 0x83, 0x5d, 0x8e, 0x9d, 0x8e, 0xd0, 0x87, 0x20, 0x34, 0x24, 0x47, 0xe5, 0xb4, 0xc9,
	0x11, 0x41, 0xe0, 0x61, 0x9b, 0x90, 0x19, 0x61, 0x32, 0xad, 0x4b, 0x58, 0xad, 0x9c, 0x21, 0x94,
	0xe5, 0x21, 0x55, 0x78, 0xf7, 0x60, 0x73, 0xee, 0xb1, 0xf1, 0x39, 0x99, 0xb8, 0xa3, 0x59, 0x38,
	0x7e, 0x4b, 0xd5, 0x13, 0xae, 0xa2, 0xd0, 0x23, 0x01, 0x8a, 0xdd, 0x62, 0x7f, 0x3e, 0x27, 0x13,
	0xd7, 0x4b, 0x8a, 0xce, 0x54, 0x48, 0x8b, 0xed, 0xbf, 0x06, 0x33, 0x7d, 0x45, 0xa1, 0x1d, 0x40,
	0x67, 0x2f, 0xda, 0xf8, 0x95, 0x3b, 0x7c, 0xf5, 0xbc, 0xed, 0xbe, 0xe8, 0x7d, 0xdf, 0xeb, 0xff,
	0xd0, 0xb3, 0x37, 0x90, 0x09, 0xf9, 0x61, 0xeb, 0xa8, 0xdb, 0xb6, 0x35, 0xb4, 0x05, 0xd6, 0xb0,
	0x73, 0xda, 0x76, 0x07, 0x6d, 0xdc, 0x69, 0x0f, 0x6c, 0x1d, 0xd9, 0x50, 0x7e, 0xda, 0x19, 0x0c,
	0x71, 0xe7, 0xe8, 0xc5, 0xb0, 0xd3, 0xef, 0xd9, 0x06, 0xb2, 0xa0, 0x38, 0x68, 0x9d, 0x3e, 0xef,
	0xb6, 0x07, 0x76, 0x6e, 0xff, 0x6b, 0x28, 0xaa, 0xf7, 0x07, 0xda, 0x06, 0x5b, 0x5a, 0xef, 0x3f,
	0xcf, 0xd8, 0xb6, 0xa0, 0xd8, 0x7a, 0xd9, 0xc6, 0xad, 0x63, 0x6e, 0xbd, 0x02, 0xe6, 0x49, 0x67,
	0x30, 0xec, 0x1f, 0xe3, 0xd6, 0xa9, 0xad, 0xef, 0x87, 0xaa, 0xfe, 0x92, 0x87, 0x24, 0xba, 0x0b,
	0xb7, 0xa5, 0x89, 0x67, 0x9d, 0xee, 0xb0, 0x8d, 0x2f, 0x5b, 0x2a, 0x80, 0x8e, 0xb9, 0x91, 0x22,
	0x18, 0x3d, 0xdc, 0xb6, 0x75, 0x0e, 0xb4, 0xcf, 0x6c, 0x43, 0x00, 0xed, 0x33, 0x3b, 0xc7, 0x81,
	0xe3, 0xa1, 0x9d, 0xe7, 0xbf, 0xdd, 0xa1, 0x5d, 0xe0, 0xbf, 0x9d, 0x9e, 0x5d, 0x14, 0x84, 0x4e,
	0xcf, 0x2e, 0xed, 0x0f, 0xa1, 0x72, 0x69, 0xe6, 0xa3, 0x3a, 0xec, 0xa4, 0x07, 0x5a, 0xf7, 0xca,
	0x36, 0xd8, 0xbd, 0x3e, 0x3e, 0x6d, 0x75, 0xdd, 0xd5, 0x99, 0x35, 0x54, 0x85, 0x4a, 0xb7, 0x7f,
	0x9c, 0x81, 0xf4, 0xc3, 0xdf, 0x75, 0xc8, 0x0f, 0xf8, 0x3f, 0x05, 0x3e, 0x8a, 0xe5, 0x3b, 0x04,
	0x89, 0xf7, 0xc5, 0xa5, 0x37, 0x7f, 0x1d, 0x65, 0x21, 0x19, 0x64, 0x67, 0x03, 0x35, 0x21, 0x2f,
	0x7c, 0x80, 0xec, 0x4c, 0xf3, 0x90, 0x0a, 0xd5, 0x6c, 0x3b, 0x49, 0xf8, 0xdf, 0x00, 0xac, 0x7a,
	0x01, 0xfa, 0x80, 0x53, 0xae, 0x34, 0x8c, 0xfa, 0xce, 0x3a, 0x9c, 0xaa, 0x3f, 0x82, 0x52, 0xd2,
	0x1c, 0xd0, 0x2d, 0xce, 0x5a, 0x6b, 0x15, 0x75, 0x93, 0x83, 0x02, 0x71, 0x36, 0xd0, 0x27, 0x90,
	0xe3, 0x39, 0x89, 0x44, 0x63, 0xcb, 0x94, 0x50, 0xdd, 0x5e, 0x01, 0x89, 0xe9, 0x51, 0x41, 0xfc,
	0x41, 0x79, 0xf2, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x72, 0x0e, 0xa7, 0x26, 0x36, 0x0d, 0x00,
	0x00,
}
